name: Build

on: [push]

strategy:
  matrix:
    compiler: [gcc, clang]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build it
        env:
          CC: ${{ matrix.compiler }}
        run: make
